# .github/workflows/deploy.yml

name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/data-api .
          docker push gcr.io/$GCP_PROJECT_ID/data-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy data-api \
            --image=gcr.io/$GCP_PROJECT_ID/data-api \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
