name: "Terraform Apply"  

on:
  workflow_dispatch:

env:
  GCP_SA_KEY: "${{ secrets.GCP_SA_KEY }}"

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - name: Build the Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-image:latest .

    - name: Push the Docker image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-image:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy api-service \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-image:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars DB_HOST=${{ secrets.DB_HOST }} \
                         DB_NAME=${{ secrets.DB_NAME }} \
                         DB_USER=${{ secrets.DB_USER }} \
                         DB_PASS=${{ secrets.DB_PASS }}
