name: "Terraform Destroy"  

on:
  workflow_dispatch:

env:
  GCP_SA_KEY: "${{ secrets.GCP_SA_KEY }}"

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        
     # Install the latest version of the Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false      

        # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
          
        # Terraform Destroy
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
