name: "Terraform Apply"  

on:
  push:
    branches:
      - develop

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar ambiente de Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: abstract-aloe-426819-i2

    - name: Autenticación en GCP
      run: |
        gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
        gcloud config set project abstract-aloe-426819-i2
