name: "Terraform Apply"

push:
    branches:
      - develop  

jobs:
  steps:
  - id: 'auth'
    name: 'Authenticate to Google Cloud'
    uses: `google-github-actions/auth@v0.4.0'
    with:
      credentials_json: '${{ secrets.GCP_SA_KEY }}'
