name: "Terraform Apply"

push:
    branches:
      - develop  

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

  steps:
  - id: 'auth'
    name: 'Authenticate to Google Cloud'
    uses: 'google-github-actions/auth@v0.4.0'
    with:
      credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
