name: "Terraform Apply"

push:
    branches:
      - develop  # Cambia por la rama en la que deseas desplegar

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate Google Cloud 
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
